name: Release_Tags
on:
 push:
  tags:
    - "v*"
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SAST Scans
        run: echo Running SAST Scans

      - name: SCA Scans
        run: echo Running SCA Scans

      - name: Detect Secrets in source code
        run: echo Detecting Secrets in source code

      - name: Produce Artifacts
        run: echo Producing Artifacts

