name: Reusable Workflow Example
on: [push, pull_request, workflow_call]
jobs:
  common:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SAST Scans
        run: echo Running SAST Scans
#